import React, { useState } from 'react';
import { Alert, SafeAreaView, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { Colors, BorderRadius, Shadows, Spacing } from '@constants/colors';
import { MOCK_EVACUATION_CENTERS } from '@data/mockData';

export default function AdminCenters() {
  const [centers, setCenters] = useState(MOCK_EVACUATION_CENTERS);
  const addCenter = () => Alert.prompt('Add evacuation center', 'Enter a center name', (name) => { if (name?.trim()) setCenters((current) => [...current, { id: `ec-${current.length + 1}`, name: name.trim(), location: 'Biñan, Laguna', capacity: 250, currentOccupancy: 0, status: 'available' }]); });
  const updateCapacity = (id: string) => Alert.prompt('Update capacity', 'Enter the new capacity', (value) => { const capacity = Number(value); if (capacity > 0) setCenters((current) => current.map((center) => center.id === id ? { ...center, capacity, status: center.currentOccupancy >= capacity ? 'full' : 'available' } : center)); });
  return <SafeAreaView style={styles.safeArea}><ScrollView contentContainerStyle={styles.content}><View style={styles.heading}><View><Text style={styles.eyebrow}>FIELD RESOURCES</Text><Text style={styles.title}>Evacuation centers</Text><Text style={styles.subtitle}>Review capacity, availability, and center information.</Text></View><TouchableOpacity style={styles.primaryButton} onPress={addCenter}><MaterialCommunityIcons name="plus" color={Colors.white} size={18} /><Text style={styles.primaryText}>Add center</Text></TouchableOpacity></View><View style={styles.grid}>{centers.map((center) => { const fill = Math.min(center.currentOccupancy / center.capacity, 1); return <View style={styles.card} key={center.id}><View style={styles.cardTop}><View style={styles.centerIcon}><MaterialCommunityIcons name="home-city-outline" size={22} color={Colors.secondary} /></View><View style={[styles.badge, { backgroundColor: center.status === 'full' ? '#FCE8E8' : '#E5F3ED' }]}><Text style={{ color: center.status === 'full' ? Colors.emergency : '#167A5B', fontSize: 10, fontWeight: '800' }}>{center.status.toUpperCase()}</Text></View></View><Text style={styles.centerName}>{center.name}</Text><Text style={styles.location}><MaterialCommunityIcons name="map-marker-outline" size={14} color={Colors.textMuted} /> {center.location}</Text><View style={styles.capacityLine}><Text style={styles.capacityLabel}>Occupancy</Text><Text style={styles.capacityValue}>{center.currentOccupancy} / {center.capacity}</Text></View><View style={styles.track}><View style={[styles.fill, { width: `${fill * 100}%`, backgroundColor: fill > .9 ? Colors.emergency : Colors.secondary }]} /></View><View style={styles.cardActions}><TouchableOpacity onPress={() => Alert.alert('Edit center', `${center.name} information is ready to update.`)}><Text style={styles.action}>Edit details</Text></TouchableOpacity><TouchableOpacity onPress={() => Alert.alert('Center contact', 'Center coordinator details are available to authorized staff.')}><Text style={styles.action}>View contact</Text></TouchableOpacity></View></View>; })}</View></ScrollView></SafeAreaView>;
}

const styles = StyleSheet.create({ safeArea: { flex: 1, backgroundColor: '#F4F7F9' }, content: { padding: Spacing.xl, paddingBottom: 48, maxWidth: 1100, width: '100%', alignSelf: 'center' }, heading: { flexDirection: 'row', justifyContent: 'space-between', gap: 16, marginBottom: 22 }, eyebrow: { color: Colors.secondary, fontSize: 11, fontWeight: '800', letterSpacing: 1.2 }, title: { color: Colors.text, fontSize: 30, fontWeight: '800', marginTop: 5 }, subtitle: { color: Colors.textMuted, fontSize: 14, marginTop: 6 }, primaryButton: { flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: Colors.primary, paddingHorizontal: 15, paddingVertical: 12, borderRadius: BorderRadius.md }, primaryText: { color: Colors.white, fontWeight: '700', fontSize: 12 }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 14 }, card: { width: '31%', minWidth: 270, backgroundColor: Colors.white, padding: 17, borderRadius: BorderRadius.md, ...Shadows.sm }, cardTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, centerIcon: { width: 40, height: 40, borderRadius: 20, backgroundColor: '#E7F0F5', justifyContent: 'center', alignItems: 'center' }, badge: { paddingHorizontal: 8, paddingVertical: 5, borderRadius: 12 }, centerName: { color: Colors.text, fontSize: 14, fontWeight: '800', marginTop: 15 }, location: { color: Colors.textMuted, fontSize: 11, marginTop: 7 }, capacityLine: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 20 }, capacityLabel: { color: Colors.textMuted, fontSize: 11 }, capacityValue: { color: Colors.text, fontSize: 11, fontWeight: '700' }, track: { height: 7, backgroundColor: '#EAF0F4', borderRadius: 4, marginTop: 7, overflow: 'hidden' }, fill: { height: '100%', borderRadius: 4 }, cardActions: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 18, paddingTop: 12, borderTopWidth: 1, borderTopColor: '#EDF1F4' }, action: { color: Colors.secondary, fontSize: 11, fontWeight: '700' } });