import React, { useState } from 'react';
import { Alert, SafeAreaView, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { Colors, BorderRadius, Shadows, Spacing } from '@constants/colors';

interface Event { id: string; name: string; areas: number; status: 'Active' | 'Archived'; started: string; }
const seed: Event[] = [{ id: 'EVT-001', name: 'Typhoon Simulation', areas: 5, status: 'Active', started: 'Today, 08:00' }, { id: 'EVT-002', name: 'Flood Response Exercise', areas: 3, status: 'Archived', started: 'Sep 12, 2026' }];

export default function AdminDisasters() {
  const [events, setEvents] = useState(seed);
  const create = () => Alert.prompt('Create disaster event', 'Enter an event name', (name) => { if (name?.trim()) setEvents((current) => [...current, { id: `EVT-00${current.length + 1}`, name: name.trim(), areas: 0, status: 'Active', started: 'Just now' }]); });
  const archive = (id: string) => setEvents((current) => current.map((event) => event.id === id ? { ...event, status: 'Archived' } : event));
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><View style={styles.heading}><View><Text style={styles.eyebrow}>EVENT CONTROL</Text><Text style={styles.title}>Disaster events</Text><Text style={styles.subtitle}>Manage events that organize incidents, centers, and response activity.</Text></View><TouchableOpacity style={styles.primary} onPress={create}><MaterialCommunityIcons name="plus" size={18} color={Colors.white} /><Text style={styles.primaryText}>Create event</Text></TouchableOpacity></View><View style={styles.list}>{events.map((event) => <View style={styles.card} key={event.id}><View style={styles.icon}><MaterialCommunityIcons name="weather-hurricane" size={24} color={event.status === 'Active' ? Colors.emergency : Colors.textMuted} /></View><View style={styles.copy}><Text style={styles.name}>{event.name}</Text><Text style={styles.detail}>{event.id} · {event.areas} affected areas · Started {event.started}</Text></View><Text style={[styles.status, { color: event.status === 'Active' ? Colors.emergency : Colors.textMuted }]}>{event.status}</Text><TouchableOpacity onPress={() => Alert.alert('Edit event', `${event.name} is ready to update.`)} style={styles.action}><MaterialCommunityIcons name="pencil-outline" size={19} color={Colors.secondary} /></TouchableOpacity>{event.status === 'Active' && <TouchableOpacity onPress={() => archive(event.id)} style={styles.action}><MaterialCommunityIcons name="archive-outline" size={19} color={Colors.emergency} /></TouchableOpacity>}</View>)}</View></ScrollView></SafeAreaView>;
}

const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: '#F4F7F9' }, content: { padding: Spacing.xl, maxWidth: 1100, width: '100%', alignSelf: 'center' }, heading: { flexDirection: 'row', justifyContent: 'space-between', gap: 16, marginBottom: 22 }, eyebrow: { color: Colors.secondary, fontSize: 11, fontWeight: '800', letterSpacing: 1.2 }, title: { color: Colors.text, fontSize: 30, fontWeight: '800', marginTop: 5 }, subtitle: { color: Colors.textMuted, fontSize: 14, marginTop: 6 }, primary: { flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: Colors.primary, paddingHorizontal: 15, paddingVertical: 12, borderRadius: BorderRadius.md }, primaryText: { color: Colors.white, fontSize: 12, fontWeight: '700' }, list: { gap: 12 }, card: { flexDirection: 'row', alignItems: 'center', gap: 13, backgroundColor: Colors.white, padding: 17, borderRadius: BorderRadius.md, ...Shadows.sm }, icon: { width: 44, height: 44, borderRadius: 22, backgroundColor: '#FCE8E8', alignItems: 'center', justifyContent: 'center' }, copy: { flex: 1 }, name: { color: Colors.text, fontSize: 14, fontWeight: '800' }, detail: { color: Colors.textMuted, fontSize: 11, marginTop: 5 }, status: { fontSize: 11, fontWeight: '800' }, action: { padding: 7 } });
